In [1]:
import pandas as pd

In [3]:
fuel = pd.read_csv('fuel.csv', low_memory=False)

In [4]:
fuel.head()

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [5]:
fuel.head(10)

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
5,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1880.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
6,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1831.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
7,28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1881.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
8,27593,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,NaN,1524.0,(FFS),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
9,28455,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,NaN,1574.0,(FFS) CA model,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [6]:
fuel.tail()

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
31679,32060,2012,Mitsubishi,Lancer,Compact Cars,Front-Wheel Drive,Manual 5-Speed,NaN,113.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
31680,32063,2012,Mitsubishi,Lancer AWD,Compact Cars,All-Wheel Drive,Auto(AV-S6),NaN,116.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
31681,32065,2012,Mitsubishi,Lancer Evolution,Compact Cars,All-Wheel Drive,Auto(AM6),NaN,132.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
31682,32064,2012,Mitsubishi,Lancer Evolution,Compact Cars,All-Wheel Drive,Manual 5-Speed,NaN,131.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
31683,32106,2012,Mitsubish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
fuel = pd.read_csv('fuel.csv',usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], low_memory=False)

In [12]:
fuel.head()

,Vehicle ID,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0

In [16]:
fuel = pd.read_csv('fuel.csv',usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'], index_col='Vehicle ID', low_memory=False)

In [17]:
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0